### ISSUE TITLE
Support latest terraform version 

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/terraform-aws-bigip-module#54]
Please add support for terraform 1.0, 
worth thinking about a more relaxed version requirement or release support for latest terraform quickly after they release a new version

**Comment by trinaths** [comment]
Created INFRAANO-484 for internal tracking.

**Comment by RavinderReddyF5** [comment]
Created already: INFRAANO-482<https://jira.pdsea.f5net.com/browse/INFRAANO-482>


From: Trinath Somanchi ***@***.***>
Date: Wednesday, 18 August 2021 at 6:45 PM
To: f5devcentral/terraform-aws-bigip-module ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [f5devcentral/terraform-aws-bigip-module] Support latest terraform version (#54)

EXTERNAL MAIL: ***@***.***

Created INFRAANO-484 for internal tracking.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ff5devcentral%2Fterraform-aws-bigip-module%2Fissues%2F54%23issuecomment-901105995&data=04%7C01%7CR.CHINTHALAPALLI%40f5.com%7Cbea4674a5daa4fa340aa08d9624a3904%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637648893198053575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C3rya6WHdgLR8aNKxqwK%2F%2BfDpqRR8g2VuJ5a%2FYgvzMA%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAK4CZFMUXYMSKHCLGOTTJ7LT5OW6FANCNFSM5CII3KXQ&data=04%7C01%7CR.CHINTHALAPALLI%40f5.com%7Cbea4674a5daa4fa340aa08d9624a3904%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637648893198063561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5L%2FoYUiE0LCVIlj9sKR2lih6G%2FVbbGaqaqN8xLJpSVE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CR.CHINTHALAPALLI%40f5.com%7Cbea4674a5daa4fa340aa08d9624a3904%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637648893198063561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4l7kg3nxfLnThEqMVsQAWnHWF4LbV%2Fq%2Fio%2Fbcxk6B1k%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CR.CHINTHALAPALLI%40f5.com%7Cbea4674a5daa4fa340aa08d9624a3904%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637648893198073556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T0H0IGDitPw6tbjOJn5CNkGpMUcWv4rmiESSbaXTIkE%3D&reserved=0>.

**Comment by papineni87** [comment]
Issue is fixed in v0.9.6, please reopen the issue if you are still facing it.
